version: 0.2

env:
  secrets-manager:
    APP_SECRET: "secure-app-config:APP_SECRET"

phases:
  install:
    commands:
      - echo Installing Trivy...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
      - chmod +x trivy

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 460351657932.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Secret loaded securely
      - docker build -t secure-app .
      - ./trivy image secure-app
      - docker tag secure-app:latest 460351657932.dkr.ecr.ap-south-1.amazonaws.com/secure-app:latest

  post_build:
    commands:
      - docker push 460351657932.dkr.ecr.ap-south-1.amazonaws.com/secure-app:latest